using GuitarShop.Models;
using GuitarShop.Services;
using System.Collections.Generic;
using System.Linq;
using Type = GuitarShop.Models.Type;

namespace GuitarShop.Database
{
    public class MockGuitarInventory : IGuitarInventory
    {
        private List<Guitar> _guitars;

        public MockGuitarInventory()
        {
            if (_guitars == null)
            {
                InitializeGuitars();
            }
        }

        private void InitializeGuitars()
        {
            _guitars = new List<Guitar> {
                new Guitar { Id = 1, Price = 1499.95M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.Stratocaster, Type = Type.electric, BackWood = BackWood.Alder, TopWood = TopWood.Alder }, IsGuitarOfTheWeek = true, ImageUrl = "https://cdn.mos.cms.futurecdn.net/23bN677y2sKiYoDsFEMLCY-970-80.jpg", Description = "Designed for players seeking an affordable, stylish and versatile instrument, the Bullet® Mustang® HH is a tonal powerhouse that punches above its weight. Highlights include a thin and lightweight body, an easy-to-play “C”-shaped neck profile and a short 24” scale length that is great for small hands. This model also boasts a pair of humbucking pickups with three-way switching for sonic variety, and a string-through-body hardtail bridge for reliable tuning stability." },
                new Guitar { Id = 2, Price = 2779.95M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.Stratocaster, Type = Type.electric, BackWood = BackWood.Alder, TopWood = TopWood.Alder }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/23bN677y2sKiYoDsFEMLCY-970-80.jpg", Description = "Designed for players seeking an affordable, stylish and versatile instrument, the Bullet® Mustang® HH is a tonal powerhouse that punches above its weight. Highlights include a thin and lightweight body, an easy-to-play “C”-shaped neck profile and a short 24” scale length that is great for small hands. This model also boasts a pair of humbucking pickups with three-way switching for sonic variety, and a string-through-body hardtail bridge for reliable tuning stability." },
                new Guitar { Id = 3, Price = 1999.90M, Specifications = new GuitarSpecification { Builder = Builder.Ibanez, Model = Model.IbanezGenesisCollectionRG550, Type = Type.electric, BackWood = BackWood.Basswood, TopWood = TopWood.Basswood }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/wo4mwXrKfixGNRea3NgToh-970-80.jpg", Description = "First built in 1987, the original Ibanez RG550 is revered by rock and metal guitarists. This Genesis Collection reissue takes its ancestor's classic design and adds a few modern touches. The original's 1-piece maple neck has been upgraded with a 5-piece laminated maple/walnut one. Its versatile HSH pickup configuration has been overhauled with modern V7 and V8 humbuckers. The RG550 features a comfortably contoured basswood body, resonating with a warm growl and enough midrange definition to cut through a dense mix. Twist, bend, and dive-bomb to your heart's content, thanks to an Edge locking tremolo. Loaded with aggressive styling (including eye-grabbing black hardware), the RG550 is a fast-playing, hard-rocking tone machine." },
                new Guitar { Id = 4, Price = 799.90M, Specifications = new GuitarSpecification { Builder = Builder.Ibanez, Model = Model.IbanezGenesisCollectionRG550, Type = Type.electric, BackWood = BackWood.Basswood, TopWood = TopWood.Basswood }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/wo4mwXrKfixGNRea3NgToh-970-80.jpg", Description = "First built in 1987, the original Ibanez RG550 is revered by rock and metal guitarists. This Genesis Collection reissue takes its ancestor's classic design and adds a few modern touches. The original's 1-piece maple neck has been upgraded with a 5-piece laminated maple/walnut one. Its versatile HSH pickup configuration has been overhauled with modern V7 and V8 humbuckers. The RG550 features a comfortably contoured basswood body, resonating with a warm growl and enough midrange definition to cut through a dense mix. Twist, bend, and dive-bomb to your heart's content, thanks to an Edge locking tremolo. Loaded with aggressive styling (including eye-grabbing black hardware), the RG550 is a fast-playing, hard-rocking tone machine." },
                new Guitar { Id = 5, Price = 1290M, Specifications = new GuitarSpecification { Builder = Builder.Ibanez, Model = Model.IbanezGenesisCollectionRG550, Type = Type.electric, BackWood = BackWood.Basswood, TopWood = TopWood.Basswood }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/wo4mwXrKfixGNRea3NgToh-970-80.jpg", Description = "First built in 1987, the original Ibanez RG550 is revered by rock and metal guitarists. This Genesis Collection reissue takes its ancestor's classic design and adds a few modern touches. The original's 1-piece maple neck has been upgraded with a 5-piece laminated maple/walnut one. Its versatile HSH pickup configuration has been overhauled with modern V7 and V8 humbuckers. The RG550 features a comfortably contoured basswood body, resonating with a warm growl and enough midrange definition to cut through a dense mix. Twist, bend, and dive-bomb to your heart's content, thanks to an Edge locking tremolo. Loaded with aggressive styling (including eye-grabbing black hardware), the RG550 is a fast-playing, hard-rocking tone machine." },
                new Guitar { Id = 6, Price = 1499.80M, Specifications = new GuitarSpecification { Builder = Builder.Gibson, Model = Model.GibsonLesPaulStudio, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/6Ws48gXDSc8zSsqaaQNCs8-970-80.jpg", Description = "The Les Paul Studio embodies the essential Les Paul features with enhancements for playability and tonal versatility. The rosewood fingerboard and slim taper mahogany neck provide effortless playability and comfort. The 490R and 498T pickups provide tight, high-output humbucking performance and the two push-pull pots offer additional coil-tapping options. Now available in four fun finishes: Smokehouse Burst, Tangerine Burst, Wine Red and Ebony." },
                new Guitar { Id = 7, Price = 399.90M, Specifications = new GuitarSpecification { Builder = Builder.Gibson, Model = Model.GibsonLesPaulStudio, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/6Ws48gXDSc8zSsqaaQNCs8-970-80.jpg", Description = "The Les Paul Studio embodies the essential Les Paul features with enhancements for playability and tonal versatility. The rosewood fingerboard and slim taper mahogany neck provide effortless playability and comfort. The 490R and 498T pickups provide tight, high-output humbucking performance and the two push-pull pots offer additional coil-tapping options. Now available in four fun finishes: Smokehouse Burst, Tangerine Burst, Wine Red and Ebony." },
                new Guitar { Id = 8, Price = 2000M, Specifications = new GuitarSpecification { Builder = Builder.Gibson, Model = Model.GibsonLesPaulStudio, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/6Ws48gXDSc8zSsqaaQNCs8-970-80.jpg", Description = "The Les Paul Studio embodies the essential Les Paul features with enhancements for playability and tonal versatility. The rosewood fingerboard and slim taper mahogany neck provide effortless playability and comfort. The 490R and 498T pickups provide tight, high-output humbucking performance and the two push-pull pots offer additional coil-tapping options. Now available in four fun finishes: Smokehouse Burst, Tangerine Burst, Wine Red and Ebony." },
                new Guitar { Id = 9, Price = 1699.79M, Specifications = new GuitarSpecification { Builder = Builder.Gibson, Model = Model.GibsonLesPaulStudio, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/6Ws48gXDSc8zSsqaaQNCs8-970-80.jpg", Description = "The Les Paul Studio embodies the essential Les Paul features with enhancements for playability and tonal versatility. The rosewood fingerboard and slim taper mahogany neck provide effortless playability and comfort. The 490R and 498T pickups provide tight, high-output humbucking performance and the two push-pull pots offer additional coil-tapping options. Now available in four fun finishes: Smokehouse Burst, Tangerine Burst, Wine Red and Ebony." },
                new Guitar { Id = 10, Price = 490.90M, Specifications = new GuitarSpecification { Builder = Builder.Epiphone, Model = Model.EpiphoneLesPaulStandard, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/fheYqTF35XYdaGyD8WtBkP-970-80.jpg", Description = "The Epiphone Les Paul Standard is the world’s most popular electric guitar at a price anyone can afford, each made to the same specs and attention to detail as vintage Les Pauls. Available in Ebony, Faded Cherry Sunburst, Metallic Gold, Pelham Blue with Epiphone designed Alnico Classic™ humbuckers and Grover® machine heads." },
                new Guitar { Id = 11, Price = 299.89M, Specifications = new GuitarSpecification { Builder = Builder.Epiphone, Model = Model.EpiphoneLesPaulStandard, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/fheYqTF35XYdaGyD8WtBkP-970-80.jpg", Description = "The Epiphone Les Paul Standard is the world’s most popular electric guitar at a price anyone can afford, each made to the same specs and attention to detail as vintage Les Pauls. Available in Ebony, Faded Cherry Sunburst, Metallic Gold, Pelham Blue with Epiphone designed Alnico Classic™ humbuckers and Grover® machine heads." },
                new Guitar { Id = 12, Price = 699M, Specifications = new GuitarSpecification { Builder = Builder.Epiphone, Model = Model.EpiphoneLesPaulStandard, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/fheYqTF35XYdaGyD8WtBkP-970-80.jpg", Description = "The Epiphone Les Paul Standard is the world’s most popular electric guitar at a price anyone can afford, each made to the same specs and attention to detail as vintage Les Pauls. Available in Ebony, Faded Cherry Sunburst, Metallic Gold, Pelham Blue with Epiphone designed Alnico Classic™ humbuckers and Grover® machine heads." },
                new Guitar { Id = 13, Price = 1199.90M, Specifications = new GuitarSpecification { Builder = Builder.Epiphone, Model = Model.EpiphoneLesPaulStandard, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/fheYqTF35XYdaGyD8WtBkP-970-80.jpg", Description = "The Epiphone Les Paul Standard is the world’s most popular electric guitar at a price anyone can afford, each made to the same specs and attention to detail as vintage Les Pauls. Available in Ebony, Faded Cherry Sunburst, Metallic Gold, Pelham Blue with Epiphone designed Alnico Classic™ humbuckers and Grover® machine heads." },
                new Guitar { Id = 14, Price = 1199.90M, Specifications = new GuitarSpecification { Builder = Builder.Epiphone, Model = Model.EpiphoneLesPaulStandard, Type = Type.electric, BackWood = BackWood.Mahogany, TopWood = TopWood.Mahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/fheYqTF35XYdaGyD8WtBkP-970-80.jpg", Description = "The Epiphone Les Paul Standard is the world’s most popular electric guitar at a price anyone can afford, each made to the same specs and attention to detail as vintage Les Pauls. Available in Ebony, Faded Cherry Sunburst, Metallic Gold, Pelham Blue with Epiphone designed Alnico Classic™ humbuckers and Grover® machine heads." },
                new Guitar { Id = 15, Price = 3399.95M, Specifications = new GuitarSpecification { Builder = Builder.Martin, Model = Model.MartinD28, Type = Type.acoustic, BackWood = BackWood.EastIndianRosewood, TopWood = TopWood.SitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/VKskPLXfmf8stNV4rJoBMQ-970-80.jpg", Description = "Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!" },
                new Guitar { Id = 16, Price = 2399.95M, Specifications = new GuitarSpecification { Builder = Builder.Martin, Model = Model.MartinD28, Type = Type.acoustic, BackWood = BackWood.EastIndianRosewood, TopWood = TopWood.SitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/VKskPLXfmf8stNV4rJoBMQ-970-80.jpg", Description = "Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!" },
                new Guitar { Id = 17, Price = 1399.89M, Specifications = new GuitarSpecification { Builder = Builder.Martin, Model = Model.MartinD28, Type = Type.acoustic, BackWood = BackWood.EastIndianRosewood, TopWood = TopWood.SitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/VKskPLXfmf8stNV4rJoBMQ-970-80.jpg", Description = "Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!" },
                new Guitar { Id = 18, Price = 3899.90M, Specifications = new GuitarSpecification { Builder = Builder.Martin, Model = Model.MartinD28, Type = Type.acoustic, BackWood = BackWood.EastIndianRosewood, TopWood = TopWood.SitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/VKskPLXfmf8stNV4rJoBMQ-970-80.jpg", Description = "Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!" },
                new Guitar { Id = 19, Price = 2489M, Specifications = new GuitarSpecification { Builder = Builder.Martin, Model = Model.MartinD28, Type = Type.acoustic, BackWood = BackWood.EastIndianRosewood, TopWood = TopWood.SitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/VKskPLXfmf8stNV4rJoBMQ-970-80.jpg", Description = "Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, JOHNNY CASH, Neil Young, Bob Dylan, and so many more, Martin's legendary D-28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s.\" says Chris Martin, Chairman and CEO of Martin Guitar, \"We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.” The all new D-28 blends the rich history of the guitar with Martin’s newest and most heralded innovations. The 184 year old guitar maker has combined vintage appointments, including open gear tuners, an aged toner top, antique white accents, and a faux tortoise pickguard with a new neck profile to give D-28 enthusiasts a modern feel and comfortable playing experience. Martin has also added forward-shifted bracing to allow greater vibration of the top. The legend just got better!" },
                new Guitar { Id = 20, Price = 4999.95M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 21, Price = 1999.95M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 22, Price = 2999.95M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 23, Price = 3999M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 24, Price = 4199.95M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 25, Price = 3099.89M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 26, Price = 2299.95M, Specifications = new GuitarSpecification { Builder = Builder.Taylor, Model = Model.TaylorBuildersEditionVClassK14CE, Type = Type.acoustic, BackWood = BackWood.Koa, TopWood = TopWood.TorrefieldSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/BhbzjPSAceGcbw4bCY4SMQ-970-80.jpg", Description = "A marvel of scaled-down design, the GS Mini is a fun little acoustic cannon that has taken the world by storm. Sporting a rich, full voice that belies its compact size, the Mini is ultra-portable, yet just as comfortable to cradle in the comfort of your home, making it the ultimate modern-day parlor guitar. Featuring the easy-playing, patented Taylor neck, this edition of the Mini incorporates a solid mahogany top that yields a strong, evenly balanced response for lively strumming. And with the easy-to-add ES-Go™ pickup, you'll have a viable performance tool, too." },
                new Guitar { Id = 27, Price = 199.70M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.FenderCD60SAllMahogany, Type = Type.acoustic, BackWood = BackWood.LaminatedMahogany, TopWood = TopWood.SolidMahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/KYS88kHWNWudrBergEVMSQ-970-80.jpg", Description = "The Hummingbird Mahogany M is a powerhouse square shoulder, slim body depth, mahogany cutaway guitar. Handcrafted with the same time-tested build techniques as our most iconic models. Each Gibson Acoustic is full of expression, character, and exquisite beauty and this new modern styled instrument is no different." },
                new Guitar { Id = 28, Price = 1899.89M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.FenderCD60SAllMahogany, Type = Type.acoustic, BackWood = BackWood.LaminatedMahogany, TopWood = TopWood.SolidMahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/KYS88kHWNWudrBergEVMSQ-970-80.jpg", Description = "The Hummingbird Mahogany M is a powerhouse square shoulder, slim body depth, mahogany cutaway guitar. Handcrafted with the same time-tested build techniques as our most iconic models. Each Gibson Acoustic is full of expression, character, and exquisite beauty and this new modern styled instrument is no different." },
                new Guitar { Id = 29, Price = 789M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.FenderCD60SAllMahogany, Type = Type.acoustic, BackWood = BackWood.LaminatedMahogany, TopWood = TopWood.SolidMahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/KYS88kHWNWudrBergEVMSQ-970-80.jpg", Description = "The Hummingbird Mahogany M is a powerhouse square shoulder, slim body depth, mahogany cutaway guitar. Handcrafted with the same time-tested build techniques as our most iconic models. Each Gibson Acoustic is full of expression, character, and exquisite beauty and this new modern styled instrument is no different." },
                new Guitar { Id = 30, Price = 999.90M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.FenderCD60SAllMahogany, Type = Type.acoustic, BackWood = BackWood.LaminatedMahogany, TopWood = TopWood.SolidMahogany }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/KYS88kHWNWudrBergEVMSQ-970-80.jpg", Description = "The Hummingbird Mahogany M is a powerhouse square shoulder, slim body depth, mahogany cutaway guitar. Handcrafted with the same time-tested build techniques as our most iconic models. Each Gibson Acoustic is full of expression, character, and exquisite beauty and this new modern styled instrument is no different." },
                new Guitar { Id = 31, Price = 1400M, Specifications = new GuitarSpecification { Builder = Builder.Yamaha, Model = Model.YamahaA5RARE, Type = Type.acoustic, BackWood = BackWood.SolidRosewood, TopWood = TopWood.SolidSitkaSpruceWithARETreatment }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/d22DhyUGuqsHEXrKVQ84dQ-970-80.jpg", Description = "In 2003, Yamaha introduced the revolutionary Silent Guitar for players seeking a super - quiet practice instrument that sounded like a nice acoustic when monitored through headphones.The model was also a boon for traveling performers seeking a super - portable and stage - worthy “acoustic” that could be plugged into house sound systems.This year, the new SLG200 series Silent Guitars offer a slimmer body, a sleeker neck profile, a removable all - wood upper bout, onboard effects(room reverb, hall reverb, and chorus), a tuner, and a Yamaha Studio Response Technology preamp that blends an undersaddle piezo pickup with a digital model of a miked, high - end Yamaha acoustic guitar. For those unfamiliar with a Silent Guitar, there may be some curiosity—and even a bit of anxiety—regarding the feel of a quasi - acoustic guitar with most of its body missing.However, if you concentrate on what’s there, as opposed to what’s not there, the SLG200S’ mahogany bouts, neck, and rosewood fretboard feel quite nice.In fact, I found it easier to play right out of the case than a lot of electric guitars. The neck feels good whether fingerpicking or using a flatpick, the cutaway body makes access to the upper register a breeze, and there’s enough room near the nut for comfy, first - position cowboy chords." },
                new Guitar { Id = 32, Price = 1800M, Specifications = new GuitarSpecification { Builder = Builder.Yamaha, Model = Model.YamahaA5RARE, Type = Type.acoustic, BackWood = BackWood.SolidRosewood, TopWood = TopWood.SolidSitkaSpruceWithARETreatment }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/d22DhyUGuqsHEXrKVQ84dQ-970-80.jpg", Description = "In 2003, Yamaha introduced the revolutionary Silent Guitar for players seeking a super - quiet practice instrument that sounded like a nice acoustic when monitored through headphones.The model was also a boon for traveling performers seeking a super - portable and stage - worthy “acoustic” that could be plugged into house sound systems.This year, the new SLG200 series Silent Guitars offer a slimmer body, a sleeker neck profile, a removable all - wood upper bout, onboard effects(room reverb, hall reverb, and chorus), a tuner, and a Yamaha Studio Response Technology preamp that blends an undersaddle piezo pickup with a digital model of a miked, high - end Yamaha acoustic guitar. For those unfamiliar with a Silent Guitar, there may be some curiosity—and even a bit of anxiety—regarding the feel of a quasi - acoustic guitar with most of its body missing.However, if you concentrate on what’s there, as opposed to what’s not there, the SLG200S’ mahogany bouts, neck, and rosewood fretboard feel quite nice.In fact, I found it easier to play right out of the case than a lot of electric guitars. The neck feels good whether fingerpicking or using a flatpick, the cutaway body makes access to the upper register a breeze, and there’s enough room near the nut for comfy, first - position cowboy chords." },
                new Guitar { Id = 33, Price = 3800M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.GuildTraditionD55, Type = Type.acoustic, BackWood = BackWood.SolidIndianRosewood, TopWood = TopWood.AAASolidSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/aj6exdfTBWGsZSAD39K8yX-970-80.jpg", Description = "The re-designed CD-60S dreadnought is also available with the warm, mellow tone of an all-mahogany body. Don't let the price tag fool you; this guitar boasts upgraded features at an attractive price, including a solid mahogany top, rolled fingerboard edges and a new \"Easy-to-Play\" neck shape. The CD-60S is an entry - level Classic Design model and features mahogany back and sides and a rosewood fingerboard.The dreadnought-sized body provides traditional full-bodied tone with plenty of projection.A great choice for any aspiring player, the CD - 60S delivers a bold playing experience." },
                new Guitar { Id = 34, Price = 2800M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.GuildTraditionD55, Type = Type.acoustic, BackWood = BackWood.SolidIndianRosewood, TopWood = TopWood.AAASolidSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/aj6exdfTBWGsZSAD39K8yX-970-80.jpg", Description = "The re-designed CD-60S dreadnought is also available with the warm, mellow tone of an all-mahogany body. Don't let the price tag fool you; this guitar boasts upgraded features at an attractive price, including a solid mahogany top, rolled fingerboard edges and a new \"Easy-to-Play\" neck shape. The CD-60S is an entry - level Classic Design model and features mahogany back and sides and a rosewood fingerboard.The dreadnought-sized body provides traditional full-bodied tone with plenty of projection.A great choice for any aspiring player, the CD - 60S delivers a bold playing experience." },
                new Guitar { Id = 35, Price = 1800M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.GuildTraditionD55, Type = Type.acoustic, BackWood = BackWood.SolidIndianRosewood, TopWood = TopWood.AAASolidSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/aj6exdfTBWGsZSAD39K8yX-970-80.jpg", Description = "The re-designed CD-60S dreadnought is also available with the warm, mellow tone of an all-mahogany body. Don't let the price tag fool you; this guitar boasts upgraded features at an attractive price, including a solid mahogany top, rolled fingerboard edges and a new \"Easy-to-Play\" neck shape. The CD-60S is an entry - level Classic Design model and features mahogany back and sides and a rosewood fingerboard.The dreadnought-sized body provides traditional full-bodied tone with plenty of projection.A great choice for any aspiring player, the CD - 60S delivers a bold playing experience." },
                new Guitar { Id = 36, Price = 3000M, Specifications = new GuitarSpecification { Builder = Builder.Fender, Model = Model.GuildTraditionD55, Type = Type.acoustic, BackWood = BackWood.SolidIndianRosewood, TopWood = TopWood.AAASolidSitkaSpruce }, IsGuitarOfTheWeek = false, ImageUrl = "https://cdn.mos.cms.futurecdn.net/aj6exdfTBWGsZSAD39K8yX-970-80.jpg", Description = "The re-designed CD-60S dreadnought is also available with the warm, mellow tone of an all-mahogany body. Don't let the price tag fool you; this guitar boasts upgraded features at an attractive price, including a solid mahogany top, rolled fingerboard edges and a new \"Easy-to-Play\" neck shape. The CD-60S is an entry - level Classic Design model and features mahogany back and sides and a rosewood fingerboard.The dreadnought-sized body provides traditional full-bodied tone with plenty of projection.A great choice for any aspiring player, the CD - 60S delivers a bold playing experience." }
            };
        }


        public List<Guitar> GetAllGuitars()
        {
            return _guitars;
        }

        public Guitar GetGuitarById(int guitarId)
        {
            return _guitars.FirstOrDefault(g => g.Id == guitarId);
        }

        public List<Guitar> Search(GuitarSpecification _searchGuitar)
        {
            var matchingGuitars = new List<Guitar>();

            foreach (var guitar in _guitars)
            {
                if (guitar.Specifications.Builder != _searchGuitar.Builder) continue;
                if (guitar.Specifications.Model != _searchGuitar.Model) continue;
                if (guitar.Specifications.Type != _searchGuitar.Type) continue;
                if (guitar.Specifications.BackWood != _searchGuitar.BackWood) continue;
                if (guitar.Specifications.TopWood != _searchGuitar.TopWood) continue;
                matchingGuitars.Add(guitar);
            }

            return matchingGuitars;
        }

    }
}
